In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
# Calculate the median to fulfill the missing value
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [10]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms) 
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [14]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
reg.intercept_

np.float64(221323.00186540402)

In [22]:
reg.predict([[3000, 3, 40]])

/Users/shahinuralambhuiyan/.pyenv/versions/3.10.12/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [24]:
reg.predict([[2500, 4, 5]])

/Users/shahinuralambhuiyan/.pyenv/versions/3.10.12/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [28]:
df_predict = pd.read_csv("predict.csv")
writePrediction = reg.predict(df_predict)
df_predict['price'] = writePrediction
df_predict.to_csv("predict.csv", index=False)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- price
